#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
pyFidA: A Python version of the fid-A toolbox from Matlab, a toolbox for 
loading and processing MRS spectroscopy data. Translated with permission from 
Jamie Near. jamie.near@utoronto.ca

Created on Mon Jun  1 14:22:35 2026

@author: cbailey@sri.utoronto.ca

[More on individual toolbox components, references, etc.]
"""

# From __future__ import ?? Anything that needs to be imported here??

# Note that I'm not sure that you necessarily need to put everything into __all__
# separately. You can import pyFidA.fidA_common and not necessarily make the 
# separate functions available at the top level. But I guess that defeats the
# point of trying to make "from pyFidA import *" function like Matlab.

# I'm not sure if I need to generate these. I think, once you have a proper
# workflow from github to PyPI, these can be generated dynamically on upload?
from pyFidA._version import __version__, __version_info__

# Skipped ReturnBehaviour, Hamiltonian, and the various functions that are 
# called by RF_pulse to calculate tw1 and tbw. These are still available from
# their subpackages. eg. if you "import pyFidA" then you can get to the Hamiltonian
# object by pyFidA.fidA_sim.Hamiltonian. Likewise, you can call the function
# to calculate the time-bandwidth product for a waveform from pyFidA.fidA_rf._calc_tbw
# (It won't show up on tab-complete, depending on your settings, because of the
# underscore keeping it somewhat hidden, but it is there for programmers who
# want to access it).
# The phase function is imported into fidA_common but is not re-exported
# here because of the likelihood of clobbering other functions or variables 
# called "phase"
from pyFidA.fidA_common import BlochSimulator, FID, GAMMA_DICT, RF_pulse, FidAWarning, FidAException
GAMMA_1H=GAMMA_DICT['1H']

from pyFidA.fidA_io import (
    io_loadjmrui,
    io_readjmrui,
    io_loadspec_data,
    io_loadspec_GE,
    io_loadspec_IMA,
    io_loadspec_niimrs,
    io_loadspec_rda,
    io_loadspec_sdat,
    io_loadspec_twix,
    io_loadspec_varian,
    io_loadspec_bruk,
    io_loadspec_bruk_new,
    io_loadspec_brukNMR,
    io_loadspec_irBruk,
    io_loadspec_jmrui,
    io_writejmrui,
    io_writespec_niimrs,
    io_writespec_jmrui,
    io_readlcmcoord_getBackground,
    io_readlcmcoord,
    io_loadlcmdetail,
    io_readlcmraw,
    io_readlcmraw_basis,
    io_readlcmraw_dotraw,
    io_readlcmtab,
    io_writelcm,
    io_writelcmraw,
    io_readpta,
    io_readRF,
    io_readRFBruk,
    io_readRFtxt,
    io_loadRFwaveform,
    io_writepta,
    io_writeRF,
    io_writeRFbruk,
    io_writeRFtxt,
    )

from pyFidA.fidA_processing import (
    add_phase,
    add_phase1,
    allow_chaining,
    freqrange,
    op_HSVDfit,
    op_addNoise,
    op_addScans,
    op_addphase,
    op_addphaseSubspec,
    op_addrcvrs,
    op_alignAllScans,
    op_alignAllScans_fd,
    op_alignAverages,
    op_alignAverages_fd,
    op_alignISIS,
    op_alignMPSubspecs,
    op_alignMPSubspecs_fd,
    op_alignScans,
    op_alignScans_fd,
    op_alignrcvrs,
    op_ampScale,
    op_arsos,
    op_autophase,
    op_averaging,
    op_blockAvg,
    op_combineRcvrs,
    op_combinesubspecs,
    op_complexConj,
    op_concatAverages,
    op_concatFreq,
    op_concatSubspecs,
    op_creFit,
    op_dccorr,
    op_downsamp,
    op_ecc,
    op_ecc_klose,
    op_fddccorr,
    op_filter,
    op_fourStepCombine,
    op_freqAlignAverages,
    op_freqAlignAverages_fd,
    op_freqrange,
    op_freqshift,
    op_freqshiftSubspec,
    op_gauss,
    op_gauss_linbas,
    op_gaussianPeak,
    op_getLW,
    op_getPeakHeight,
    op_getSNR,
    op_getcoilcombos,
    op_getcoilcombos_specReg,
    op_integrate,
    op_leftshift,
    op_lorentz,
    op_lorentz_linbas,
    op_lorentzianPeak,
    op_makeECArtifact,
    op_makeFreqDrift,
    op_makePhaseDrift,
    op_matchLW,
    op_median,
    op_movef0,
    op_peakFit,
    op_phaseAlignAverages,
    op_phaseAlignAverages_fd,
    op_plotfid,
    op_plotspec,
    op_ppmref,
    op_relyTest,
    op_removeWater,
    op_rmNworstaverages,
    op_rmbadaverages,
    op_rmworstaverage,
    op_squeeze,
    op_subtractScans,
    op_takeaverages,
    op_takecoils,
    op_takeextras,
    op_takesubspec,
    op_timerange,
    op_unfilter,
    op_voigt_linbas,
    op_zeropad,
    op_zerotrim,
    stop_chaining,
    )

from pyFidA.fidA_rf import(
    rf_addGrad,
    rf_blochSim,
    rf_combineRF,
    rf_dualBand,
    rf_freqshift,
    rf_gauss,
    rf_getRFPeakPower,
    rf_getRFPulseEnergy,
    rf_goia,
    rf_hs,
    rf_plotWaveform,
    rf_refocusedComponent,
    rf_resample,
    rf_scaleGrad,
    rf_sinc,
    rf_single2dualBand,
    rf_timeReverse,
    rf_verse,
    )

from pyFidA.fidA_sim import (
    read_all_spinsys_matlab,
    read_spinsys_matlab,
    sim_COF,
    sim_coherenceOrder,
    sim_Hamiltonian,
    sim_coherenceOrder,
    sim_cosy,
    sim_dAdd,
    sim_dDiv,
    sim_dMul,
    sim_evolve,
    sim_excite,
    sim_excite_arbPh,
    sim_gradSpoil,
    sim_Hamiltonian,
    sim_laser,
    sim_lcmrawbasis,
    sim_megapress,
    sim_megapress_shaped,
    sim_megapress_shapedEdit,
    sim_megapress_shapedRefoc,
    sim_megaspecial_shaped,
    sim_onepulse,
    sim_onepulse_arbPh,
    sim_onepulse_delay,
    sim_onepulse_shaped,
    sim_press,
    sim_press_shaped,
    sim_press_shaped_phCyc,
    sim_readout,
    sim_rotate,
    sim_rotate_arbPh,
    sim_semiLASER_shaped,
    sim_semiLASER_shaped_phCyc,
    sim_shapedRF,
    sim_spinecho,
    sim_spinecho_shaped,
    sim_spinecho_xN,
    sim_spoil,
    sim_steam,
    sim_steam_shaped,
    )


# I think, if I do the sub-packages for each thing and define __all__ correctly
# for each of those, I don't need this. Actually, even then, I may not need this
# because I've only imported what I want from each sub-thing??
# __all__ = [
#     "__version__",
#     "__version_info__",
#     # classes and constants
#     "FID",
#     "GAMMA_DICT",
#     "GAMMA_1H",
#     # input/output (rf part only at this point)
#     "io_readRFBruk",
#     "io_readpta",
#     "io_readRF",
#     "io_readRFtxt",
#     "io_loadRFwaveform",
#     # processing
#     'add_phase',
#     'add_phase1',
#     'allow_chaining',
#     'freqrange',
#     'op_HSVDfit',
#     'op_addNoise',
#     'op_addScans',
#     'op_addphase',
#     'op_addphaseSubspec',
#     'op_addrcvrs',
#     'op_alignAllScans',
#     'op_alignAllScans_fd',
#     'op_alignAverages',
#     'op_alignAverages_fd',
#     'op_alignISIS',
#     'op_alignMPSubspecs',
#     'op_alignMPSubspecs_fd',
#     'op_alignScans',
#     'op_alignScans_fd',
#     'op_alignrcvrs',
#     'op_ampScale',
#     'op_arsos',
#     'op_autophase',
#     'op_averaging',
#     'op_blockAvg',
#     'op_combineRcvrs',
#     'op_combinesubspecs',
#     'op_complexConj',
#     'op_concatAverages',
#     'op_concatFreq',
#     'op_concatSubspecs',
#     'op_creFit',
#     'op_dccorr',
#     'op_downsamp',
#     'op_ecc',
#     'op_ecc_klose',
#     'op_fddccorr',
#     'op_filter',
#     'op_fourStepCombine',
#     'op_freqAlignAverages',
#     'op_freqAlignAverages_fd',
#     'op_freqrange',
#     'op_freqshift',
#     'op_freqshiftSubspec',
#     'op_gauss',
#     'op_gauss_linbas',
#     'op_gaussianPeak',
#     'op_getLW',
#     'op_getPeakHeight',
#     'op_getSNR',
#     'op_getcoilcombos',
#     'op_getcoilcombos_specReg',
#     'op_integrate',
#     'op_leftshift',
#     'op_lorentz',
#     'op_lorentz_linbas',
#     'op_lorentzianPeak',
#     'op_makeECArtifact',
#     'op_makeFreqDrift',
#     'op_makePhaseDrift',
#     'op_matchLW',
#     'op_median',
#     'op_movef0',
#     'op_peakFit',
#     'op_phaseAlignAverages',
#     'op_phaseAlignAverages_fd',
#     'op_plotfid',
#     'op_plotspec',
#     'op_ppmref',
#     'op_relyTest',
#     'op_removeWater',
#     'op_rmNworstaverages',
#     'op_rmbadaverages',
#     'op_rmworstaverage',
#     'op_subtractScans',
#     'op_takeaverages',
#     'op_takecoils',
#     'op_takeextras',
#     'op_takesubspec',
#     'op_timerange',
#     'op_unfilter',
#     'op_voigt_linbas',
#     'op_zeropad',
#     'op_zerotrim',
#     'stop_chaining',
#     # Simulation toolbox
#     'sim_COF',
#     'sim_Hamiltonian',
#     'sim_coherenceOrder',
#     'sim_cosy',
#     'sim_dAdd',
#     'sim_dDiv',
#     'sim_dMul',
#     'sim_evolve',
#     'sim_excite',
#     'sim_excite_arbPh',
#     'sim_gradSpoil',
#     'sim_laser',
#     'sim_lcmrawbasis',
#     'sim_make2DSimPlot',
#     'sim_megapress',
#     'sim_megapress_shaped',
#     'sim_megapress_shapedEdit',
#     'sim_megapress_shapedRefoc',
#     'sim_megaspecial_shaped',
#     'sim_onepulse',
#     'sim_onepulse_arbPh',
#     'sim_onepulse_delay',
#     'sim_onepulse_shaped',
#     'sim_press',
#     'sim_press_shaped',
#     'sim_press_shaped_phCyc',
#     'sim_readout',
#     'sim_rotate',
#     'sim_rotate_arbPh',
#     'sim_semiLASER_shaped',
#     'sim_semiLASER_shaped_phCyc',
#     'sim_shapedRF',
#     'sim_spinecho',
#     'sim_spinecho_shaped',
#     'sim_spinecho_xN',
#     'sim_spoil',
#     'sim_steam',
#     'sim_steam_shaped',
#     ]